Updated patchtool
* Added checking of critical patches
* Added dry run
* Cosmetic changes

diff --git a/patches/patchtool b/patches/patchtool
--- a/patches/patchtool
+++ b/patches/patchtool
@@ -31,20 +31,21 @@ function helpcommand() {
 	echo ""
 	echo "Optional arguments:"
 	echo "-V, --verbose        print errors, other messages"
+	echo "-D, --dry-run        do not actually make changes, generate random errors if --apply specified"
 }
 
 function finishcommand() {
 	necho
-	if [[ ! $FIXMENUM == 0 ]] ; then
+	if [[ ! $FIXMENUM == 0 ]]; then
 		echo -ne "${BI_MAGENTA}Fix $FIXMENUM patches.${NC} "
 	fi
-	if [[ ! $ALREADYPATCHEDNUM == 0 ]] ; then
+	if [[ ! $ALREADYPATCHEDNUM == 0 ]]; then
 		echo -ne "${BI_BLUE}$ALREADYPATCHEDNUM repos already patched.${NC} "
 	fi
-	if [[ ! $ERRORNUM == 0 ]] ; then
+	if [[ ! $ERRORNUM == 0 ]]; then
 		echo -ne "${RED}Found $ERRORNUM errors.${NC} "
 	fi
-	if [[ ! $OKNUM == 0 ]] ; then
+	if [[ ! $OKNUM == 0 ]]; then
 		echo -ne "${GREEN}$OKNUM actions were completed.${NC} "
 	fi
 	necho
@@ -53,16 +54,16 @@ function finishcommand() {
 function checkrom() {
 	local ROM=$1
 
-	if [[ -z $ROM && -z $DEFAULT ]] ; then
+	if [[ -z $ROM && -z $DEFAULT ]]; then
 		echo -e "${RED}You must specify ROM when patching.${NC}"
 		exit 1
-	elif [[ -z $ROM ]] ; then
+	elif [[ -z $ROM ]]; then
 		echo -e "${BLUE}No ROM specified, using the default '$DEFAULT'${NC}"
 		INPUTROM=$DEFAULT
 		ROM=$DEFAULT
 	fi
 
-	if [[ ! -e $ROM ]] ; then
+	if [[ ! -e $ROM ]]; then
 		echo -e "${RED}Directory '$ROM' not found.${NC}"
 		exit 1
 	fi
@@ -71,7 +72,7 @@ function checkrom() {
 function checkcommon() {
 	local ROM="common"
 
-	if [[ ! -e $ROM ]] ; then
+	if [[ ! -e $ROM ]]; then
 		echo -e "${BI_MAGENTA}Directory '$ROM' not found. Creating it...${NC}"
 		mkdir "common"
 	fi
@@ -79,7 +80,7 @@ function checkcommon() {
 
 function notifyfixme() {
 	# Check patches listed as 'to fix', and show reminder
-	if [[ $LINE == *".fixme" ]] ; then
+	if [[ $LINE == *".fixme" ]]; then
 		echo -e "${BI_MAGENTA}Hey, you should fix $ROM/$LINE${NC}"
 		FIXMENUM=$(($FIXMENUM+1))
 		continue
@@ -100,30 +101,44 @@ function clearpatchescommand() {
 
 		echo -ne "${BLUE}Clearing repository${NC}"
 
-		cd $TOPDIR
-		if [[ ! -e $REPO ]] ; then
+		cd "$TOPDIR"
+		if [[ ! -e $REPO ]]; then
 			echo -e " -> ${RED}Repository ${YELLOW}$REPO${RED} does not exist. Skipping...${NC}"
 			CLEARED="$CLEARED|$REPO|"
-			cd $THISDIR
+			cd "$THISDIR"
 			ERRORNUM=$(($ERRORNUM+1))
 			continue
 		fi
 
 		echo -e " -> ${YELLOW}$REPO${NC}"
 
-		cd $REPO
-		git add . > /dev/null
-		git stash > /dev/null
-		find -name *.orig | while read LINE; do rm $LINE; done
-		find -name *.rej | while read LINE; do rm $LINE; done
-		git clean -f > /dev/null
-		git stash clear > /dev/null
+		cd "$REPO"
+		if [[ $DRYRUN == false ]]; then
+			git add . > /dev/null
+			git stash > /dev/null
+			find -name "*.orig" | while read LINE; do rm "$LINE"; done
+			find -name "*.rej" | while read LINE; do rm "$LINE"; done
+			git clean -f > /dev/null
+			git stash clear > /dev/null
+		fi
 		CLEARED="$CLEARED|$REPO|"
-		cd $THISDIR
+		cd "$THISDIR"
 		OKNUM=$(($OKNUM+1))
 	done
-	if [[ $LINENUM == 0 ]] ; then
+	if [[ $LINENUM == 0 ]]; then
 		echo -e "${BLUE}No patches were found in this directory.${NC}"
+	fi
+}
+
+function checkcritical() {
+	if [[ $GOTERROR == true ]]; then
+		if [[ $CRITICAL == true ]]; then
+			necho
+			echo -e "${BI_RED}Critical error occured: $COLOREDLINE ${BI_RED}is needed for booting/building the ROM!${NC}"
+			echo -e "${BGI_RED}You cannot proceed without this patch, so fix it!${NC}"
+			exit 1
+		fi
+		continue
 	fi
 }
 
@@ -133,7 +148,7 @@ function patchcommand() {
 
 	necho
 	echo -e "${BI_MAGENTA}Entering directory $ROM${NC}"
-	cd $ROM
+	cd "$ROM"
 	for LINE in $(find -L -name '*.patch' -or -name '*.patch.fixme' | cut -c 3- | sort)
 	do
 
@@ -141,65 +156,80 @@ function patchcommand() {
 
 		LINENUM=$(($LINENUM+1))
 		PATCH="$THISDIR/$ROM/$LINE"
+		CRITICAL=false
+		GOTERROR=false
+		COLOREDLINE="${YELLOW}$LINE${NC}"
 
-		echo -ne "${BLUE}Applying patch: ${YELLOW}$LINE${NC}"
+		if [[ $(echo "$COLOREDLINE" | grep -c "critical") -gt 0 ]]; then
+			COLOREDLINE=$(echo "$COLOREDLINE" | sed -e "s/critical/\x1b[101mcritical\x1b[0m\x1b[93m/g")
+			CRITICAL=true
+		fi
+
+		echo -ne "${BLUE}Applying patch: $COLOREDLINE"
 
 		REPO=$(dirname $LINE)
 
 		echo -ne " -> ${YELLOW}$REPO${NC}"
-		cd $TOPDIR
+		cd "$TOPDIR"
 		if [[ ! -e $REPO ]]; then
 			echo -e " -> ${RED}Repository ${YELLOW}$SHORTREPO${RED} does not exist. Skipping...${NC}"
-			cd $THISDIR
+			cd "$THISDIR"
 			ERRORNUM=$(($ERRORNUM+1))
-			continue
+			GOTERROR=true
+			checkcritical
 		fi
 
-		cd $REPO
-		RESULT=$(patch '-p1' '--follow-symlinks' '--no-backup-if-mismatch' < $PATCH 2>&1)
-		cd $THISDIR
+		cd "$REPO"
+		if [[ $DRYRUN == false ]]; then
+			RESULT=$(patch '-p1' '--follow-symlinks' '--no-backup-if-mismatch' < $PATCH 2>&1)
+		else
+			RESULT=$(patch '--dry-run' '-p1' '--follow-symlinks' '--no-backup-if-mismatch' < $PATCH 2>&1)
+		fi
+		cd "$THISDIR"
 
 		# Show the patch result
-		if [[ $MESSAGE == true ]] ; then
+		if [[ $MESSAGE == true ]]; then
 			echo -e "\n -> ${RESULT}"
 		fi
 
-		if [[ $(echo $RESULT | grep -c "Reversed (or previously applied) patch detected") -gt 0 ]] ; then
+		if [[ $(echo $RESULT | grep -c "Reversed (or previously applied) patch detected") -gt 0 ]]; then
 			echo -e  " -> ${BI_BLUE}Already patched. Skipping...${NC}"
-			cd $REPO
-			find -name *.orig | while read LINE; do rm $LINE; done
-			find -name *.rej | while read LINE; do rm $LINE; done
-			cd $THISDIR
+			cd "$TOPDIR"/"$REPO"
+			if [[ $DRYRUN == false ]]; then
+				find -name "*.orig" | while read LINE; do rm "$LINE"; done
+				find -name "*.rej" | while read LINE; do rm "$LINE"; done
+			fi
+			cd "$THISDIR"
 			ALREADYPATCHEDNUM=$(($ALREADYPATCHEDNUM+1))
 			continue
-		fi
-		if [[ $(echo $RESULT | grep -c "can't find") -gt 0 ]] ; then
-			echo -e " -> ${RED}Can't find specific file. Skipping...${NC}"
+		elif [[ $(echo $RESULT | grep -c "can't find") -gt 0 ]]; then
+			echo -e " -> ${RED}Can't find specified file. Skipping...${NC}"
 			ERRORNUM=$(($ERRORNUM+1))
-			continue
-		fi
-		if [[ $(echo $RESULT | grep -c FAILED) -gt 0 ]] ; then
+			GOTERROR=true
+			checkcritical
+		elif [[ $(echo $RESULT | grep -c FAILED) -gt 0 ]]; then
 			echo -e " -> ${RED}Patch failed. Skipping...${NC}"
 			ERRORNUM=$(($ERRORNUM+1))
-			continue
-		fi
-		if [[ $(echo $RESULT | grep -c "saving rejects to file") -gt 0 ]] ; then
+			GOTERROR=true
+			checkcritical
+		elif [[ $(echo $RESULT | grep -c "saving rejects to file") -gt 0 ]]; then
 			echo -e  " -> ${RED}Patch rejected, edit target manually. Skipping...${NC}"
 			ERRORNUM=$(($ERRORNUM+1))
-			continue
-		fi
-		if [[ $(echo $RESULT | grep -c "garbage\|malformed") -gt 0 ]] ; then
+			GOTERROR=true
+			checkcritical
+		elif [[ $(echo $RESULT | grep -c "garbage\|malformed") -gt 0 ]]; then
 			echo -e  " -> ${RED}Invalid syntax. Skipping...${NC}"
 			ERRORNUM=$(($ERRORNUM+1))
-			continue
+			GOTERROR=true
+			checkcritical
 		fi
 
 		echo -e  " -> ${GREEN}Done${NC}"
 		OKNUM=$(($OKNUM+1))
 	done
-	if [[ $LINENUM == 0 ]] ; then
+	if [[ $LINENUM == 0 ]]; then
 		echo -e "${BLUE}No patches were found in '$ROM'${NC}"
-		cd $THISDIR
+		cd "$THISDIR"
 	fi
 }
 
@@ -209,7 +239,7 @@ function applycommand() {
 
 	necho
 	echo -e "${BI_MAGENTA}Entering directory $ROM${NC}"
-	cd $ROM
+	cd "$ROM"
 	for LINE in $(find -L -name '*.apply' -or -name '*.apply.fixme' | cut -c 3- | sort)
 	do
 
@@ -217,45 +247,64 @@ function applycommand() {
 
 		LINENUM=$(($LINENUM+1))
 		PATCH="$THISDIR/$ROM/$LINE"
+		CRITICAL=false
+		GOTERROR=false
+		COLOREDLINE="${YELLOW}$LINE${NC}"
 
-		echo -ne "${BLUE}Applying patch: ${YELLOW}$LINE${NC}"
+		if [[ $(echo "$COLOREDLINE" | grep -c "critical") -gt 0 ]]; then
+			COLOREDLINE=$(echo "$COLOREDLINE" | sed -e "s/critical/\x1b[101mcritical\x1b[0m\x1b[93m/g")
+			CRITICAL=true
+		fi
+
+		echo -ne "${BLUE}Applying patch: $COLOREDLINE"
 
 		REPO=$(dirname $LINE)
 
 		echo -ne " -> ${YELLOW}$REPO${NC}"
-		cd $TOPDIR
+		cd "$TOPDIR"
 		if [[ ! -e $REPO ]]; then
 			echo -e " -> ${RED}Repository ${YELLOW}$REPO${RED} does not exist. Skipping...${NC}"
-			cd $THISDIR
+			cd "$THISDIR"
 			ERRORNUM=$(($ERRORNUM+1))
-			continue
+			GOTERROR=true
+            checkcritical
 		fi
 
-		cd $REPO
-		RESULT=$(git apply --whitespace=nowarn -v $PATCH 2>&1)
-		cd $THISDIR
+		cd "$REPO"
+		if [[ $DRYRUN == false ]]; then
+			RESULT=$(git apply --whitespace=nowarn -v $PATCH 2>&1)
+		else
+			RAND=$(echo $RANDOM % 2 | bc)
+			if [[ $RAND == 0 ]]; then
+				RESULT="success: dry run!"
+			else
+				RESULT="error: dry run!"
+			fi
+		fi
+		cd "$THISDIR"
 
 		# show the patch result
 		if [[ $MESSAGE == true ]]; then
 			echo -e "\n -> ${RESULT}"
 		fi
 
-		if [[ $(echo $RESULT | grep -c error:) -gt 0 ]] ; then
+		if [[ $(echo $RESULT | grep -c "error:") -gt 0 ]]; then
 			echo -e " -> ${RED}Patch failed. Skipping...${NC}"
 			ERRORNUM=$(($ERRORNUM+1))
-			continue
+			GOTERROR=true
+            checkcritical
 		fi
 
 		echo -e  " -> ${GREEN}Done${NC}"
 		OKNUM=$(($OKNUM+1))
 	done
-	if [[ $LINENUM == 0 ]] ; then
+	if [[ $LINENUM == 0 ]]; then
 		echo -e "${BLUE}No patches were found in '$ROM'${NC}"
-		cd $THISDIR
+		cd "$THISDIR"
 	fi
 }
 
-if [[ ! $# -gt 0 ]] ; then
+if [[ ! $# -gt 0 ]]; then
 	invalidargs
 	exit 1
 fi
@@ -269,15 +318,19 @@ OKNUM=0
 FIXMENUM=0
 ALREADYPATCHEDNUM=0
 
+DRYRUN=false
+
 # TODO: Add non-coloured variant
 NC='\033[0m' # No Color
 RED='\033[0;91m'
 BLUE='\033[0;94m'
 YELLOW='\033[0;93m'
 GREEN='\033[0;92m'
+BI_RED='\033[1;91m'
 BI_MAGENTA='\033[1;95m'
 BI_YELLOW='\033[1;93m'
 BI_BLUE='\033[1;96m'
+BGI_RED='\033[1;101m'
 
 while [[ $# -gt 0 ]]
 do
@@ -285,6 +338,10 @@ do
 	case $arg in
 		-V|--verbose)
 		MESSAGE=true
+		;;
+		-D|--dry-run)
+		echo -e "${BGI_RED}Running dry run${NC}"
+		DRYRUN=true
 		;;
 		-ap|-pa)
 		ACTION=true
@@ -329,6 +386,7 @@ do
 		-c|--clear)
 		ACTION=true
 		necho
+		echo -e "${BI_YELLOW}Finding patched repositories...${NC}"
 		clearpatchescommand
 		finishcommand
 		;;
